<a href="https://colab.research.google.com/github/zakieassad/pcb-defect-detection-yolo/blob/main/notebooks/04_colab_final_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

print(f"PyTorch: {torch.__version__}")
print(f"CUDA disponible: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

PyTorch: 2.11.0+cu128
CUDA disponible: True
GPU: Tesla T4

In [2]:
!git clone https://github.com/zakieassad/pcb-defect-detection-yolo.git
%cd pcb-defect-detection-yolo

Cloning into 'pcb-defect-detection-yolo'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 35 (delta 12), reused 25 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (35/35), 665.03 KiB | 2.76 MiB/s, done.
Resolving deltas: 100% (12/12), done.
/content/pcb-defect-detection-yolo

In [3]:
!pip install -q -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 105.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 910.8/910.8 kB 61.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.5/77.5 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 kB 37.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 117.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires jupyter-server==2.18.2, but you have jupyter-server 2.20.0 which is incompatible.

In [4]:
from ultralytics import YOLO
import ultralytics
import torch

print("Ultralytics:", ultralytics.__version__)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics: 8.4.87
CUDA: True
GPU: Tesla T4

In [5]:
from pathlib import Path
import shutil

import cv2
import pandas as pd
from sklearn.model_selection import train_test_split

# =========================
# RUTAS
# =========================

PROJECT_ROOT = Path.cwd()

DATA_RAW_DIR = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

DATA_RAW_DIR.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# Descargar DeepPCB
!wget -q https://github.com/tangsanli5201/DeepPCB/archive/refs/heads/master.zip -O data/raw/DeepPCB-master.zip
!unzip -q data/raw/DeepPCB-master.zip -d data/raw/

DEEPPCB_DIR = DATA_RAW_DIR / "DeepPCB-master"
PCB_DATA_DIR = DEEPPCB_DIR / "PCBData"

TRAINVAL_FILE = PCB_DATA_DIR / "trainval.txt"
TEST_FILE = PCB_DATA_DIR / "test.txt"

YOLO_DATASET_DIR = DATA_PROCESSED_DIR / "deep_pcb_yolo"

assert DEEPPCB_DIR.exists(), "No se encontró DeepPCB."
assert PCB_DATA_DIR.exists(), "No se encontró PCBData."
assert TRAINVAL_FILE.exists(), "No se encontró trainval.txt."
assert TEST_FILE.exists(), "No se encontró test.txt."

print("Dataset original descargado correctamente.")


# =========================
# FUNCIONES
# =========================

def read_split_file(file_path: Path) -> list[str]:
    with open(file_path, "r", encoding="utf-8") as file:
        return [line.strip() for line in file if line.strip()]


def resolve_test_image_path(image_rel_path: str) -> Path:
    logical_path = PCB_DATA_DIR / image_rel_path

    if logical_path.exists():
        return logical_path

    return logical_path.with_name(
        logical_path.stem + "_test" + logical_path.suffix
    )


def build_samples_dataframe(samples: list[str], original_split: str) -> pd.DataFrame:
    records = []

    for sample in samples:
        image_rel_path, annotation_rel_path = sample.split()

        records.append({
            "sample_id": Path(image_rel_path).stem,
            "group": Path(image_rel_path).parts[0],
            "original_split": original_split,
            "image_path": resolve_test_image_path(image_rel_path),
            "annotation_path": PCB_DATA_DIR / annotation_rel_path,
        })

    return pd.DataFrame(records)


def validate_original_bbox(
    x_min: int,
    y_min: int,
    x_max: int,
    y_max: int,
    image_width: int,
    image_height: int,
) -> None:
    assert 0 <= x_min < x_max <= image_width
    assert 0 <= y_min < y_max <= image_height


def convert_bbox_to_yolo(
    x_min: int,
    y_min: int,
    x_max: int,
    y_max: int,
    image_width: int,
    image_height: int,
) -> tuple[float, float, float, float]:
    box_width = x_max - x_min
    box_height = y_max - y_min

    x_center = x_min + box_width / 2
    y_center = y_min + box_height / 2

    return (
        x_center / image_width,
        y_center / image_height,
        box_width / image_width,
        box_height / image_height,
    )


def convert_annotation_file_to_yolo(annotation_path: Path, image_path: Path) -> list[str]:
    image = cv2.imread(str(image_path))

    if image is None:
        raise ValueError(f"No se pudo leer la imagen: {image_path}")

    image_height, image_width = image.shape[:2]
    yolo_lines = []

    with open(annotation_path, "r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            line = line.strip()

            if not line:
                continue

            values = line.split()

            if len(values) != 5:
                raise ValueError(
                    f"Formato inválido en {annotation_path}, línea {line_number}: {line}"
                )

            x_min, y_min, x_max, y_max, original_class_id = map(int, values)

            if original_class_id not in range(1, 7):
                raise ValueError(
                    f"Clase inválida {original_class_id} en {annotation_path}, línea {line_number}"
                )

            validate_original_bbox(
                x_min=x_min,
                y_min=y_min,
                x_max=x_max,
                y_max=y_max,
                image_width=image_width,
                image_height=image_height,
            )

            x_center, y_center, box_width, box_height = convert_bbox_to_yolo(
                x_min=x_min,
                y_min=y_min,
                x_max=x_max,
                y_max=y_max,
                image_width=image_width,
                image_height=image_height,
            )

            yolo_class_id = original_class_id - 1

            yolo_lines.append(
                f"{yolo_class_id} "
                f"{x_center:.6f} "
                f"{y_center:.6f} "
                f"{box_width:.6f} "
                f"{box_height:.6f}"
            )

    return yolo_lines


def reset_yolo_dataset_directory(output_dir: Path) -> None:
    if output_dir.exists():
        shutil.rmtree(output_dir)

    for split_name in ["train", "val", "test"]:
        (output_dir / "images" / split_name).mkdir(parents=True, exist_ok=True)
        (output_dir / "labels" / split_name).mkdir(parents=True, exist_ok=True)


def process_split(split_df: pd.DataFrame, split_name: str, output_dir: Path) -> dict:
    images_output_dir = output_dir / "images" / split_name
    labels_output_dir = output_dir / "labels" / split_name

    processed_images = 0
    processed_labels = 0
    processed_annotations = 0

    for _, sample in split_df.iterrows():
        source_image_path = sample["image_path"]
        source_annotation_path = sample["annotation_path"]

        target_image_path = images_output_dir / f"{sample['sample_id']}{source_image_path.suffix}"
        target_label_path = labels_output_dir / f"{sample['sample_id']}.txt"

        shutil.copy2(source_image_path, target_image_path)

        yolo_annotations = convert_annotation_file_to_yolo(
            annotation_path=source_annotation_path,
            image_path=source_image_path,
        )

        with open(target_label_path, "w", encoding="utf-8") as file:
            file.write("\n".join(yolo_annotations))
            if yolo_annotations:
                file.write("\n")

        processed_images += 1
        processed_labels += 1
        processed_annotations += len(yolo_annotations)

    return {
        "split": split_name,
        "images": processed_images,
        "label_files": processed_labels,
        "annotations": processed_annotations,
    }


# =========================
# RECONSTRUCCIÓN DE SPLITS
# =========================

trainval_samples = read_split_file(TRAINVAL_FILE)
test_samples = read_split_file(TEST_FILE)

df_trainval = build_samples_dataframe(trainval_samples, original_split="trainval")
df_test = build_samples_dataframe(test_samples, original_split="test")

df_train, df_val = train_test_split(
    df_trainval,
    test_size=0.20,
    random_state=42,
    stratify=df_trainval["group"],
)

df_test_final = df_test.copy()

print(f"Train: {len(df_train)} imágenes")
print(f"Validation: {len(df_val)} imágenes")
print(f"Test: {len(df_test_final)} imágenes")


# =========================
# GENERACIÓN DATASET YOLO
# =========================

reset_yolo_dataset_directory(YOLO_DATASET_DIR)

processing_results = [
    process_split(df_train, "train", YOLO_DATASET_DIR),
    process_split(df_val, "val", YOLO_DATASET_DIR),
    process_split(df_test_final, "test", YOLO_DATASET_DIR),
]

df_processing_results = pd.DataFrame(processing_results)
display(df_processing_results)

assert df_processing_results["images"].sum() == 1500
assert df_processing_results["label_files"].sum() == 1500
assert df_processing_results["annotations"].sum() == 10013

print("Dataset YOLO generado correctamente.")


# =========================
# DATA.YAML
# =========================

data_yaml_content = f"""path: {YOLO_DATASET_DIR.as_posix()}
train: images/train
val: images/val
test: images/test

names:
  0: open
  1: short
  2: mousebite
  3: spur
  4: copper
  5: pin-hole
"""

data_yaml_path = YOLO_DATASET_DIR / "data.yaml"

with open(data_yaml_path, "w", encoding="utf-8") as file:
    file.write(data_yaml_content)

print(data_yaml_content)
print(f"data.yaml creado en: {data_yaml_path}")

Dataset original descargado correctamente.
Train: 800 imágenes
Validation: 200 imágenes
Test: 500 imágenes

   split  images  label_files  annotations
0  train     800          800         5513
1    val     200          200         1360
2   test     500          500         3140

Dataset YOLO generado correctamente.
path: /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo
train: images/train
val: images/val
test: images/test

names:
  0: open
  1: short
  2: mousebite
  3: spur
  4: copper
  5: pin-hole

data.yaml creado en: /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/data.yaml

In [6]:
from ultralytics import YOLO
from pathlib import Path
import torch
import time

PROJECT_ROOT = Path.cwd()
RUNS_DIR = PROJECT_ROOT / "runs"
DATA_YAML_PATH = PROJECT_ROOT / "data" / "processed" / "deep_pcb_yolo" / "data.yaml"

print("CUDA disponible:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print("data.yaml:", DATA_YAML_PATH)

CUDA disponible: True
GPU: Tesla T4
data.yaml: /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/data.yaml

In [7]:
start_time = time.time()

model_nano = YOLO("yolo11n.pt")

results_nano = model_nano.train(
    data=str(DATA_YAML_PATH),
    epochs=50,
    imgsz=640,
    batch=16,
    device=0,
    project=str(RUNS_DIR),
    name="yolo11n_deeppcb",
    workers=2,
    seed=42,
    patience=10,
    exist_ok=True
)

elapsed_time_nano = time.time() - start_time

print(f"Tiempo total YOLO11n: {elapsed_time_nano / 60:.2f} minutos")

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 80.7MB/s 0.1s
Ultralytics 8.4.87 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11n_deeppcb, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/pcb-defect-detection-yolo/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 27.1MB/s 0.0s
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    431842  ultralytics.nn.modules.head.Detect           [6, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,591,010 parameters, 2,590,994 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 95.6MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 463.2±297.3 MB/s, size: 13.3 KB)
train: Scanning /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/train... 800 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 800/800 2.1Kit/s 0.4s
train: New cache created: /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 281.2±29.0 MB/s, size: 21.6 KB)
val: Scanning /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/val... 200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 200/200 1.8Kit/s 0.1s
val: New cache created: /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50       2.3G      2.436      4.175      1.515        188        640: 100% ━━━━━━━━━━━━ 50/50 2.0it/s 25.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 1.3s/it 9.2s
                   all        200       1360     0.0152      0.578     0.0602     0.0142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50       2.9G       1.69      2.654      1.154        150        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 2.7it/s 2.6s
                   all        200       1360      0.339      0.107      0.266      0.102

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50       2.9G      1.507      1.998      1.082        117        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 2.6it/s 2.7s
                   all        200       1360      0.388      0.458      0.387      0.133

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50       2.9G      1.463      1.706      1.075        161        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.1it/s 1.7s
                   all        200       1360      0.349      0.275      0.197     0.0359

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50       2.9G      1.352      1.458      1.037        160        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.2it/s 1.7s
                   all        200       1360       0.73      0.755      0.814      0.541

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50       2.9G      1.324      1.312       1.02        109        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.0it/s 1.8s
                   all        200       1360      0.811      0.792      0.859      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50       2.9G      1.314      1.215      1.017        150        640: 100% ━━━━━━━━━━━━ 50/50 3.9it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.7it/s 1.9s
                   all        200       1360      0.861      0.817      0.892      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50       2.9G      1.279      1.151      1.014        144        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.8it/s 1.5s
                   all        200       1360      0.885      0.826      0.916      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50       2.9G      1.316      1.122      1.008        113        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.0it/s 2.3s
                   all        200       1360      0.903      0.834      0.924      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50       2.9G      1.282      1.075      1.005        183        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.6it/s 2.0s
                   all        200       1360      0.918      0.866      0.943      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50       2.9G      1.223      1.028     0.9966        131        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.8it/s 1.5s
                   all        200       1360      0.885      0.845      0.923       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50       2.9G      1.206      1.013      0.987        201        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.8it/s 1.4s
                   all        200       1360      0.879      0.858       0.92      0.465

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50       2.9G      1.198     0.9624     0.9764        126        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.1it/s 1.7s
                   all        200       1360      0.918       0.88      0.946      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50       2.9G      1.162     0.9245      0.976        165        640: 100% ━━━━━━━━━━━━ 50/50 3.6it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.8it/s 1.4s
                   all        200       1360      0.895      0.892      0.945       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50       2.9G      1.138     0.9037     0.9651        138        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 2.8it/s 2.5s
                   all        200       1360       0.93      0.872      0.955      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50       2.9G      1.127     0.8767      0.958        180        640: 100% ━━━━━━━━━━━━ 50/50 4.0it/s 12.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.1it/s 2.2s
                   all        200       1360      0.913       0.91      0.955      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50       2.9G      1.108      0.857     0.9581        165        640: 100% ━━━━━━━━━━━━ 50/50 3.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.6it/s 1.5s
                   all        200       1360      0.928      0.904      0.959        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50       2.9G      1.124     0.8603     0.9586        174        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.0it/s 1.8s
                   all        200       1360      0.944      0.898      0.968      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50       2.9G      1.085     0.8176     0.9502        133        640: 100% ━━━━━━━━━━━━ 50/50 3.9it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.3it/s 2.1s
                   all        200       1360      0.952      0.886       0.96      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50       2.9G      1.082     0.8085     0.9511        145        640: 100% ━━━━━━━━━━━━ 50/50 3.6it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.2it/s 1.7s
                   all        200       1360      0.905      0.872      0.933      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50       2.9G      1.091     0.7803     0.9456        202        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.4it/s 1.6s
                   all        200       1360      0.947      0.912       0.97      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50       2.9G      1.106     0.7842     0.9495        108        640: 100% ━━━━━━━━━━━━ 50/50 3.6it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.1it/s 2.3s
                   all        200       1360      0.949       0.92       0.97      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50       2.9G      1.064     0.7444     0.9333        162        640: 100% ━━━━━━━━━━━━ 50/50 3.8it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.1it/s 1.7s
                   all        200       1360      0.933      0.924       0.97        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50       2.9G      1.041     0.7465     0.9365        143        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.2it/s 1.7s
                   all        200       1360      0.951      0.932      0.976      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50       2.9G      1.064     0.7402      0.941        163        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.8it/s 1.4s
                   all        200       1360      0.946      0.915      0.965      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50       2.9G      1.017     0.7132     0.9245        172        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 5.0it/s 1.4s
                   all        200       1360      0.956      0.923      0.971       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50       2.9G      1.029     0.7255     0.9303        184        640: 100% ━━━━━━━━━━━━ 50/50 3.7it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.4it/s 1.6s
                   all        200       1360      0.944      0.928      0.977      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50       2.9G       1.01     0.6959     0.9257        123        640: 100% ━━━━━━━━━━━━ 50/50 3.6it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.1it/s 2.3s
                   all        200       1360      0.966      0.931      0.977      0.701
EarlyStopping: Training stopped early as no improvement observed in last 10 epochs. Best results observed at epoch 18, best model saved as best.pt.
To update EarlyStopping(patience=10) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

28 epochs completed in 0.127 hours.
Optimizer stripped from /content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb/weights/last.pt, 5.5MB
Optimizer stripped from /content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb/weights/best.pt, 5.5MB

Validating /content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb/weights/best.pt...
Ultralytics 8.4.87 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11n summary (fused): 101 layers, 2,583,322 parameters, 0 gradients, 6.3 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 1.9it/s 3.7s
                   all        200       1360      0.945      0.898      0.968      0.705
                  open        171        262      0.983       0.87       0.98       0.65
                 short        141        204      0.875      0.902      0.958       0.63
             mousebite        177        281      0.917       0.89      0.953      0.673
                  spur        171        233       0.97      0.901      0.959       0.66
                copper        157        185       0.95      0.962       0.98      0.813
              pin-hole        174        195      0.976      0.862      0.981      0.802
Speed: 0.2ms preprocess, 2.8ms inference, 0.0ms loss, 3.9ms postprocess per image
Results saved to /content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb
Tiempo total YOLO11n: 8.16 minutos

In [8]:
start_time = time.time()

model_small = YOLO("yolo11s.pt")

results_small = model_small.train(
    data=str(DATA_YAML_PATH),
    epochs=50,
    imgsz=640,
    batch=16,
    device=0,
    project=str(RUNS_DIR),
    name="yolo11s_deeppcb",
    workers=2,
    seed=42,
    patience=10,
    exist_ok=True
)

elapsed_time_small = time.time() - start_time

print(f"Tiempo total YOLO11s: {elapsed_time_small / 60:.2f} minutos")

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11s.pt to 'yolo11s.pt': 100% ━━━━━━━━━━━━ 18.4MB 170.3MB/s 0.1s
Ultralytics 8.4.87 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11s_deeppcb, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/pcb-defect-detection-yolo/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    821730  ultralytics.nn.modules.head.Detect           [6, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,430,114 parameters, 9,430,098 gradients, 21.6 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 665.5±416.9 MB/s, size: 17.3 KB)
train: Scanning /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/train.cache... 800 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 800/800 279.6Mit/s 0.0s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 210.6±78.8 MB/s, size: 18.4 KB)
val: Scanning /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/val.cache... 200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 200/200 7.4Mit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      4.19G      2.358      3.396      1.516        188        640: 100% ━━━━━━━━━━━━ 50/50 2.3it/s 22.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 1.4it/s 4.9s
                   all        200       1360      0.245      0.228      0.159     0.0304

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      5.41G       1.51       1.47      1.084        150        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.7it/s 1.9s
                   all        200       1360      0.644      0.577      0.564      0.153

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      5.41G      1.469       1.18      1.072        117        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.8it/s 1.9s
                   all        200       1360      0.372      0.347      0.269     0.0556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      5.41G      1.344      1.057      1.032        161        640: 100% ━━━━━━━━━━━━ 50/50 3.3it/s 15.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.9it/s 1.8s
                   all        200       1360      0.821      0.765      0.853      0.366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      5.41G        1.3     0.9792      1.024        160        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.3it/s 2.1s
                   all        200       1360      0.852      0.812      0.879      0.348

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      5.41G      1.221     0.8864     0.9888        109        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.9it/s 1.8s
                   all        200       1360       0.61      0.548      0.502      0.106

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      5.41G      1.255     0.8689     0.9981        150        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.8it/s 1.8s
                   all        200       1360      0.926      0.865      0.949      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      5.41G      1.195     0.8128     0.9915        144        640: 100% ━━━━━━━━━━━━ 50/50 3.3it/s 15.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 2.9it/s 2.4s
                   all        200       1360      0.565      0.477      0.403     0.0915

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      5.41G      1.176     0.7665     0.9767        113        640: 100% ━━━━━━━━━━━━ 50/50 3.3it/s 15.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 4.0it/s 1.8s
                   all        200       1360       0.91      0.844      0.918      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      5.41G      1.218     0.7711     0.9909        183        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.9it/s 1.8s
                   all        200       1360      0.733      0.695      0.734      0.231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      5.41G      1.189     0.7713     0.9897        131        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 2.8it/s 2.5s
                   all        200       1360      0.945      0.883      0.959      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      5.41G      1.136      0.743     0.9692        201        640: 100% ━━━━━━━━━━━━ 50/50 3.3it/s 15.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.9it/s 1.8s
                   all        200       1360      0.802      0.747      0.773      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      5.41G      1.075      0.695     0.9534        126        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.8it/s 1.8s
                   all        200       1360      0.951      0.898      0.967      0.744

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      5.41G      1.056     0.6678     0.9515        165        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.0it/s 2.4s
                   all        200       1360      0.951      0.908      0.964      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      5.41G      1.063      0.671     0.9485        138        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.8it/s 1.8s
                   all        200       1360      0.905      0.821      0.878      0.279

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      5.41G      1.114       0.67     0.9572        180        640: 100% ━━━━━━━━━━━━ 50/50 3.3it/s 15.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.9it/s 1.8s
                   all        200       1360      0.931      0.876      0.949      0.435

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      5.41G      1.069     0.6483      0.948        165        640: 100% ━━━━━━━━━━━━ 50/50 3.1it/s 15.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.3it/s 2.1s
                   all        200       1360      0.913      0.878      0.933      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      5.41G       1.07     0.6484      0.949        174        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.9it/s 1.8s
                   all        200       1360      0.944      0.929       0.97      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      5.41G      1.035     0.6053     0.9399        133        640: 100% ━━━━━━━━━━━━ 50/50 3.3it/s 15.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.8it/s 1.8s
                   all        200       1360      0.948      0.921      0.969      0.508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      5.41G      1.095     0.6355     0.9547        145        640: 100% ━━━━━━━━━━━━ 50/50 3.1it/s 15.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.6it/s 2.0s
                   all        200       1360      0.699      0.675      0.614      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      5.41G      1.032     0.5955     0.9334        202        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.7it/s 1.9s
                   all        200       1360      0.821      0.789        0.8      0.206

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      5.41G      1.069     0.6227     0.9413        108        640: 100% ━━━━━━━━━━━━ 50/50 3.2it/s 15.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.5it/s 2.0s
                   all        200       1360      0.945      0.878       0.95      0.509

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      5.41G      1.002     0.5772     0.9219        162        640: 100% ━━━━━━━━━━━━ 50/50 3.1it/s 15.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 3.6it/s 1.9s
                   all        200       1360      0.835      0.818      0.835      0.253
EarlyStopping: Training stopped early as no improvement observed in last 10 epochs. Best results observed at epoch 13, best model saved as best.pt.
To update EarlyStopping(patience=10) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

23 epochs completed in 0.119 hours.
Optimizer stripped from /content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb/weights/last.pt, 19.2MB
Optimizer stripped from /content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb/weights/best.pt, 19.2MB

Validating /content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb/weights/best.pt...
Ultralytics 8.4.87 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11s summary (fused): 101 layers, 9,415,122 parameters, 0 gradients, 21.3 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 7/7 1.7it/s 4.1s
                   all        200       1360      0.948      0.902      0.967      0.744
                  open        171        262       0.94      0.956      0.984      0.685
                 short        141        204      0.857       0.88      0.939      0.636
             mousebite        177        281      0.942      0.925       0.97      0.731
                  spur        171        233      0.963      0.887      0.956      0.718
                copper        157        185      0.994      0.893      0.983      0.859
              pin-hole        174        195      0.994      0.874      0.967      0.833
Speed: 0.3ms preprocess, 6.0ms inference, 0.0ms loss, 5.3ms postprocess per image
Results saved to /content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb
Tiempo total YOLO11s: 7.41 minutos

In [9]:
for run_name in ["yolo11n_deeppcb", "yolo11s_deeppcb"]:
    run_dir = RUNS_DIR / run_name
    print(f"\n{run_name}")
    print("Existe:", run_dir.exists())

    if run_dir.exists():
        for file in sorted(run_dir.iterdir()):
            print("-", file.name)

yolo11n_deeppcb
Existe: True
- BoxF1_curve.png
- BoxPR_curve.png
- BoxP_curve.png
- BoxR_curve.png
- args.yaml
- confusion_matrix.png
- confusion_matrix_normalized.png
- labels.jpg
- results.csv
- results.png
- train_batch0.jpg
- train_batch1.jpg
- train_batch2.jpg
- val_batch0_labels.jpg
- val_batch0_pred.jpg
- val_batch1_labels.jpg
- val_batch1_pred.jpg
- val_batch2_labels.jpg
- val_batch2_pred.jpg
- weights

yolo11s_deeppcb
Existe: True
- BoxF1_curve.png
- BoxPR_curve.png
- BoxP_curve.png
- BoxR_curve.png
- args.yaml
- confusion_matrix.png
- confusion_matrix_normalized.png
- labels.jpg
- results.csv
- results.png
- train_batch0.jpg
- train_batch1.jpg
- train_batch2.jpg
- val_batch0_labels.jpg
- val_batch0_pred.jpg
- val_batch1_labels.jpg
- val_batch1_pred.jpg
- val_batch2_labels.jpg
- val_batch2_pred.jpg
- weights

In [10]:
best_nano_path = RUNS_DIR / "yolo11n_deeppcb" / "weights" / "best.pt"
best_small_path = RUNS_DIR / "yolo11s_deeppcb" / "weights" / "best.pt"

model_nano_best = YOLO(str(best_nano_path))
model_small_best = YOLO(str(best_small_path))

test_results_nano = model_nano_best.val(
    data=str(DATA_YAML_PATH),
    split="test",
    imgsz=640,
    batch=16,
    device=0,
    project=str(RUNS_DIR),
    name="yolo11n_test",
    exist_ok=True
)

test_results_small = model_small_best.val(
    data=str(DATA_YAML_PATH),
    split="test",
    imgsz=640,
    batch=16,
    device=0,
    project=str(RUNS_DIR),
    name="yolo11s_test",
    exist_ok=True
)

Ultralytics 8.4.87 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11n summary (fused): 101 layers, 2,583,322 parameters, 0 gradients, 6.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 220.4±174.0 MB/s, size: 29.6 KB)
val: Scanning /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/test... 500 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 500/500 586.0it/s 0.9s
val: New cache created: /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 5.1it/s 6.3s
                   all        500       3140      0.922      0.907      0.954      0.686
                  open        482        659      0.973      0.832      0.961      0.612
                 short        368        478      0.701      0.864      0.863      0.542
             mousebite        413        586      0.961      0.922      0.975      0.668
                  spur        373        483      0.963      0.914      0.961      0.675
                copper        403        464      0.952      0.966      0.979      0.825
              pin-hole        438        470      0.984      0.942      0.984      0.791
Speed: 1.8ms preprocess, 4.0ms inference, 0.0ms loss, 1.3ms postprocess per image
Results saved to /content/pcb-defect-detection-yolo/runs/yolo11n_test
Ultralytics 8.4.87 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11s summary (fused): 101 layers, 9,415,122 parameters, 0 gradients, 21.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1072.8±206.3 MB/s, size: 23.4 KB)
val: Scanning /content/pcb-defect-detection-yolo/data/processed/deep_pcb_yolo/labels/test.cache... 500 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 500/500 123.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.8s
                   all        500       3140      0.939      0.914      0.962      0.723
                  open        482        659      0.938      0.943      0.966      0.623
                 short        368        478      0.814      0.864      0.898      0.595
             mousebite        413        586      0.971       0.93      0.972        0.7
                  spur        373        483       0.98      0.886      0.967      0.714
                copper        403        464      0.971      0.929      0.984      0.879
              pin-hole        438        470       0.96      0.934      0.983      0.829
Speed: 3.2ms preprocess, 9.9ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to /content/pcb-defect-detection-yolo/runs/yolo11s_test

In [11]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()
RUNS_DIR = PROJECT_ROOT / "runs"

for path in sorted(RUNS_DIR.iterdir()):
    if path.is_dir():
        print(path)

/content/pcb-defect-detection-yolo/runs/yolo11n_deeppcb
/content/pcb-defect-detection-yolo/runs/yolo11n_test
/content/pcb-defect-detection-yolo/runs/yolo11s_deeppcb
/content/pcb-defect-detection-yolo/runs/yolo11s_test

In [12]:
import pandas as pd

run_names = [
    "yolo11n_deeppcb",
    "yolo11s_deeppcb",
]

for run_name in run_names:
    results_path = RUNS_DIR / run_name / "results.csv"
    print(f"\n{run_name}")
    print("Existe:", results_path.exists())

    if results_path.exists():
        df = pd.read_csv(results_path)
        display(df.tail())

yolo11n_deeppcb
Existe: True

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
23,24,394.643,1.04107,0.74648,0.93654,0.95106,0.93208,0.97592,0.67546,1.02334,0.64060,0.94827,0.000545,0.000545,0.000545
24,25,409.993,1.06442,0.74020,0.94099,0.94594,0.91529,0.96545,0.58253,1.24636,0.75994,1.00838,0.000525,0.000525,0.000525
25,26,425.360,1.01663,0.71316,0.92446,0.95607,0.92331,0.97061,0.53003,1.53269,0.77748,1.09339,0.000505,0.000505,0.000505
26,27,441.086,1.02916,0.72554,0.93027,0.94354,0.92800,0.97715,0.70304,0.96645,0.63119,0.93900,0.000485,0.000485,0.000485
27,28,457.727,1.00985,0.69586,0.92567,0.96639,0.93116,0.97724,0.70093,0.99208,0.60294,0.93959,0.000465,0.000465,0.000465

yolo11s_deeppcb
Existe: True

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
18,19,353.021,1.03544,0.60532,0.93988,0.94760,0.92080,0.96923,0.50834,1.56546,0.65127,1.10898,0.000644,0.000644,0.000644
19,20,371.767,1.09519,0.63552,0.95474,0.69859,0.67458,0.61394,0.12598,3.00867,1.08422,1.81668,0.000624,0.000624,0.000624
20,21,389.698,1.03202,0.59549,0.93335,0.82079,0.78882,0.79996,0.20631,2.68463,0.93437,1.62180,0.000604,0.000604,0.000604
21,22,408.029,1.06881,0.62275,0.94134,0.94524,0.87778,0.95014,0.50940,1.50298,0.66520,1.09238,0.000584,0.000584,0.000584
22,23,426.753,1.00172,0.57717,0.92188,0.83532,0.81822,0.83494,0.25304,2.48760,0.88514,1.49623,0.000564,0.000564,0.000564

In [13]:
test_run_names = [
    "yolo11n_test",
    "yolo11s_test",
]

for run_name in test_run_names:
    results_path = RUNS_DIR / run_name / "results.csv"
    print(f"\n{run_name}")
    print("Existe:", results_path.exists())

    if results_path.exists():
        df = pd.read_csv(results_path)
        display(df.tail())

yolo11n_test
Existe: False

yolo11s_test
Existe: False

In [14]:
for run_name in [
    "yolo11n_deeppcb",
    "yolo11s_deeppcb",
    "yolo11n_test",
    "yolo11s_test",
]:
    run_dir = RUNS_DIR / run_name

    print(f"\n{run_name}")
    if run_dir.exists():
        for file in sorted(run_dir.iterdir()):
            print("-", file.name)

yolo11n_deeppcb
- BoxF1_curve.png
- BoxPR_curve.png
- BoxP_curve.png
- BoxR_curve.png
- args.yaml
- confusion_matrix.png
- confusion_matrix_normalized.png
- labels.jpg
- results.csv
- results.png
- train_batch0.jpg
- train_batch1.jpg
- train_batch2.jpg
- val_batch0_labels.jpg
- val_batch0_pred.jpg
- val_batch1_labels.jpg
- val_batch1_pred.jpg
- val_batch2_labels.jpg
- val_batch2_pred.jpg
- weights

yolo11s_deeppcb
- BoxF1_curve.png
- BoxPR_curve.png
- BoxP_curve.png
- BoxR_curve.png
- args.yaml
- confusion_matrix.png
- confusion_matrix_normalized.png
- labels.jpg
- results.csv
- results.png
- train_batch0.jpg
- train_batch1.jpg
- train_batch2.jpg
- val_batch0_labels.jpg
- val_batch0_pred.jpg
- val_batch1_labels.jpg
- val_batch1_pred.jpg
- val_batch2_labels.jpg
- val_batch2_pred.jpg
- weights

yolo11n_test
- BoxF1_curve.png
- BoxPR_curve.png
- BoxP_curve.png
- BoxR_curve.png
- confusion_matrix.png
- confusion_matrix_normalized.png
- val_batch0_labels.jpg
- val_batch0_pred.jpg
- val_batch1_labels.jpg
- val_batch1_pred.jpg
- val_batch2_labels.jpg
- val_batch2_pred.jpg

yolo11s_test
- BoxF1_curve.png
- BoxPR_curve.png
- BoxP_curve.png
- BoxR_curve.png
- confusion_matrix.png
- confusion_matrix_normalized.png
- val_batch0_labels.jpg
- val_batch0_pred.jpg
- val_batch1_labels.jpg
- val_batch1_pred.jpg
- val_batch2_labels.jpg
- val_batch2_pred.jpg

In [15]:
PROJECT_ROOT = Path.cwd()
RUNS_DIR = PROJECT_ROOT / "runs"

def extract_test_metrics(results, model_name):
    """
    Extrae métricas principales de un resultado de validación YOLO.
    """
    box = results.box

    return {
        "model": model_name,
        "precision": float(box.mp),
        "recall": float(box.mr),
        "mAP50": float(box.map50),
        "mAP50_95": float(box.map),
    }


test_metrics = pd.DataFrame([
    extract_test_metrics(test_results_nano, "YOLO11n"),
    extract_test_metrics(test_results_small, "YOLO11s"),
])

test_metrics

     model  precision    recall     mAP50  mAP50_95
0  YOLO11n   0.922457  0.906759  0.953771  0.685606
1  YOLO11s   0.938966  0.914269  0.961891  0.723329

In [16]:
metrics_dir = PROJECT_ROOT / "results" / "metrics"
metrics_dir.mkdir(parents=True, exist_ok=True)

test_metrics_path = metrics_dir / "test_metrics_summary.csv"

test_metrics.to_csv(test_metrics_path, index=False)

print(f"Métricas guardadas en: {test_metrics_path}")
display(test_metrics)

Métricas guardadas en: /content/pcb-defect-detection-yolo/results/metrics/test_metrics_summary.csv

     model  precision    recall     mAP50  mAP50_95
0  YOLO11n   0.922457  0.906759  0.953771  0.685606
1  YOLO11s   0.938966  0.914269  0.961891  0.723329

In [17]:
CLASS_NAMES = [
    "open",
    "short",
    "mousebite",
    "spur",
    "copper",
    "pin-hole",
]

def extract_class_metrics(results, model_name):
    """
    Extrae métricas por clase desde un resultado de validación YOLO.
    """
    box = results.box

    rows = []

    for idx, class_name in enumerate(CLASS_NAMES):
        rows.append({
            "model": model_name,
            "class_id": idx,
            "class_name": class_name,
            "precision": float(box.p[idx]),
            "recall": float(box.r[idx]),
            "mAP50": float(box.ap50[idx]),
            "mAP50_95": float(box.ap[idx]),
        })

    return rows


class_metrics = pd.DataFrame(
    extract_class_metrics(test_results_nano, "YOLO11n")
    + extract_class_metrics(test_results_small, "YOLO11s")
)

class_metrics_path = metrics_dir / "test_metrics_by_class.csv"

class_metrics.to_csv(class_metrics_path, index=False)

display(class_metrics)
print(f"Métricas por clase guardadas en: {class_metrics_path}")

      model  class_id class_name  precision    recall     mAP50  mAP50_95
0   YOLO11n         0       open   0.973386  0.832486  0.960576  0.611563
1   YOLO11n         1      short   0.700790  0.864017  0.863129  0.542447
2   YOLO11n         2  mousebite   0.960880  0.922128  0.975155  0.667924
3   YOLO11n         3       spur   0.962924  0.914127  0.960720  0.675406
4   YOLO11n         4     copper   0.952324  0.965517  0.978986  0.825264
5   YOLO11n         5   pin-hole   0.984440  0.942277  0.984061  0.791032
6   YOLO11s         0       open   0.938077  0.942514  0.966499  0.623456
7   YOLO11s         1      short   0.813637  0.864017  0.898452  0.594920
8   YOLO11s         2  mousebite   0.971478  0.930034  0.971534  0.699904
9   YOLO11s         3       spur   0.980151  0.886128  0.967215  0.714028
10  YOLO11s         4     copper   0.970723  0.928879  0.984390  0.878936
11  YOLO11s         5   pin-hole   0.959731  0.934043  0.983253  0.828733

Métricas por clase guardadas en: /content/pcb-defect-detection-yolo/results/metrics/test_metrics_by_class.csv

In [18]:
!zip -r final_yolo_results.zip runs results

  adding: runs/ (stored 0%)
  adding: runs/yolo11n_deeppcb/ (stored 0%)
  adding: runs/yolo11n_deeppcb/val_batch1_pred.jpg (deflated 17%)
  adding: runs/yolo11n_deeppcb/args.yaml (deflated 54%)
  adding: runs/yolo11n_deeppcb/results.png (deflated 7%)
  adding: runs/yolo11n_deeppcb/BoxR_curve.png (deflated 9%)
  adding: runs/yolo11n_deeppcb/weights/ (stored 0%)
  adding: runs/yolo11n_deeppcb/weights/best.pt (deflated 10%)
  adding: runs/yolo11n_deeppcb/weights/last.pt (deflated 10%)
  adding: runs/yolo11n_deeppcb/train_batch2.jpg (deflated 14%)
  adding: runs/yolo11n_deeppcb/BoxF1_curve.png (deflated 7%)
  adding: runs/yolo11n_deeppcb/labels.jpg (deflated 30%)
  adding: runs/yolo11n_deeppcb/val_batch0_labels.jpg (deflated 17%)
  adding: runs/yolo11n_deeppcb/val_batch1_labels.jpg (deflated 19%)
  adding: runs/yolo11n_deeppcb/val_batch0_pred.jpg (deflated 15%)
  adding: runs/yolo11n_deeppcb/confusion_matrix_normalized.png (deflated 20%)
  adding: runs/yolo11n_deeppcb/BoxP_curve.png (deflated 8%)
  adding: runs/yolo11n_deeppcb/val_batch2_pred.jpg (deflated 23%)
  adding: runs/yolo11n_deeppcb/val_batch2_labels.jpg (deflated 26%)
  adding: runs/yolo11n_deeppcb/confusion_matrix.png (deflated 23%)
  adding: runs/yolo11n_deeppcb/results.csv (deflated 60%)
  adding: runs/yolo11n_deeppcb/train_batch0.jpg (deflated 12%)
  adding: runs/yolo11n_deeppcb/train_batch1.jpg (deflated 12%)
  adding: runs/yolo11n_deeppcb/BoxPR_curve.png (deflated 14%)
  adding: runs/yolo11s_test/ (stored 0%)
  adding: runs/yolo11s_test/val_batch1_pred.jpg (deflated 14%)
  adding: runs/yolo11s_test/BoxR_curve.png (deflated 10%)
  adding: runs/yolo11s_test/BoxF1_curve.png (deflated 7%)
  adding: runs/yolo11s_test/val_batch0_labels.jpg (deflated 17%)
  adding: runs/yolo11s_test/val_batch1_labels.jpg (deflated 16%)
  adding: runs/yolo11s_test/val_batch0_pred.jpg (deflated 16%)
  adding: runs/yolo11s_test/confusion_matrix_normalized.png (deflated 21%)
  adding: runs/yolo11s_test/BoxP_curve.png (deflated 8%)
  adding: runs/yolo11s_test/val_batch2_pred.jpg (deflated 21%)
  adding: runs/yolo11s_test/val_batch2_labels.jpg (deflated 25%)
  adding: runs/yolo11s_test/confusion_matrix.png (deflated 22%)
  adding: runs/yolo11s_test/BoxPR_curve.png (deflated 13%)
  adding: runs/yolo11s_deeppcb/ (stored 0%)
  adding: runs/yolo11s_deeppcb/val_batch1_pred.jpg (deflated 17%)
  adding: runs/yolo11s_deeppcb/args.yaml (deflated 54%)
  adding: runs/yolo11s_deeppcb/results.png (deflated 5%)
  adding: runs/yolo11s_deeppcb/BoxR_curve.png (deflated 10%)
  adding: runs/yolo11s_deeppcb/weights/ (stored 0%)
  adding: runs/yolo11s_deeppcb/weights/best.pt (deflated 8%)
  adding: runs/yolo11s_deeppcb/weights/last.pt (deflated 8%)
  adding: runs/yolo11s_deeppcb/train_batch2.jpg (deflated 14%)
  adding: runs/yolo11s_deeppcb/BoxF1_curve.png (deflated 8%)
  adding: runs/yolo11s_deeppcb/labels.jpg (deflated 30%)
  adding: runs/yolo11s_deeppcb/val_batch0_labels.jpg (deflated 17%)
  adding: runs/yolo11s_deeppcb/val_batch1_labels.jpg (deflated 19%)
  adding: runs/yolo11s_deeppcb/val_batch0_pred.jpg (deflated 15%)
  adding: runs/yolo11s_deeppcb/confusion_matrix_normalized.png (deflated 20%)
  adding: runs/yolo11s_deeppcb/BoxP_curve.png (deflated 9%)
  adding: runs/yolo11s_deeppcb/val_batch2_pred.jpg (deflated 24%)
  adding: runs/yolo11s_deeppcb/val_batch2_labels.jpg (deflated 26%)
  adding: runs/yolo11s_deeppcb/confusion_matrix.png (deflated 24%)
  adding: runs/yolo11s_deeppcb/results.csv (deflated 59%)
  adding: runs/yolo11s_deeppcb/train_batch0.jpg (deflated 12%)
  adding: runs/yolo11s_deeppcb/train_batch1.jpg (deflated 12%)
  adding: runs/yolo11s_deeppcb/BoxPR_curve.png (deflated 14%)
  adding: runs/yolo11n_test/ (stored 0%)
  adding: runs/yolo11n_test/val_batch1_pred.jpg (deflated 13%)
  adding: runs/yolo11n_test/BoxR_curve.png (deflated 9%)
  adding: runs/yolo11n_test/BoxF1_curve.png (deflated 6%)
  adding: runs/yolo11n_test/val_batch0_labels.jpg (deflated 17%)
  adding: runs/yolo11n_test/val_batch1_labels.jpg (deflated 16%)
  adding: runs/yolo11n_test/val_batch0_pred.jpg (deflated 14%)
  adding: runs/yolo11n_test/confusion_matrix_normalized.png (deflated 20%)
  adding: runs/yolo11n_test/BoxP_curve.png (deflated 8%)
  adding: runs/yolo11n_test/val_batch2_pred.jpg (deflated 21%)
  adding: runs/yolo11n_test/val_batch2_labels.jpg (deflated 25%)
  adding: runs/yolo11n_test/confusion_matrix.png (deflated 21%)
  adding: runs/yolo11n_test/BoxPR_curve.png (deflated 12%)
  adding: results/ (stored 0%)
  adding: results/metrics/ (stored 0%)
  adding: results/metrics/test_metrics_summary.csv (deflated 32%)
  adding: results/metrics/test_metrics_by_class.csv (deflated 51%)
  adding: results/.gitkeep (stored 0%)

In [19]:
from google.colab import files
files.download("final_yolo_results.zip")